# Generated by Django 2.2 on 2019-06-26 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateField(blank=True, verbose_name=datetime.datetime),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='photos',
            field=models.ImageField(upload_to='photos/%Y/%M/%d/'),
        ),
    ]
